### ISSUE TITLE
I made a better Captcha script

### ISSUE THREAD

**Issue by the-wazir** [clonemeagain/awesome-osticket#9]
Hey,

I made a better and very customizable Captcha script which is a simple drop-in replacement of the core /include/class.captcha.php file.  It'd be great if you could list it on your page.  From what I can see it should be compatible right down to v1.7

I will post about it on the forum (once they activate me) but you can access it here:
https://github.com/the-wazir/osTicket

I would be delighted if you could add it to your awesome list - it saved me so much time when setting up my first osTicket installation and I'd love to give something back! :)

Cheers,

Simon.

**Comment by clonemeagain** [comment]
I suppose the "themes" are technically mods, if you want to open a pull request in a new category, sure.
